# Generated by Django 5.0 on 2023-12-24 19:52

import apps.products.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("category_image", models.ImageField(upload_to="categories/")),
                ("category_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scans",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "scan_id",
                    models.CharField(
                        db_index=True,
                        default=apps.products.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("scan_image", models.ImageField(upload_to="scanned/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "product_id",
                    models.CharField(
                        db_index=True,
                        default=apps.products.models.short_uuid,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_name", models.CharField(max_length=250)),
                ("product_image", models.ImageField(upload_to="products/")),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("size", models.IntegerField(blank=True, default=0)),
                ("discount", models.FloatField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("exp_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categories",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
