# Generated by Django 5.0 on 2023-12-25 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
